# Site settings
title: Theodore Vasiloudis' personal website.
email: tvas@sics.se
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website for Theodore Vasiloudis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tvas.me" # the base hostname & protocol for your site
twitter_username: thvasilo
github_username:  thvasilo

# Build settings
markdown: kramdown
