# Site settings
title: Theodore Vasiloudis
email: tvas@sics.se
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website for Theodore Vasiloudis.
  Here I will post thoughts and experiences on large-scale machine learning,
  including algorithms, systems and related stuff I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tvas.me" # the base hostname & protocol for your site
twitter_username: thvasilo
github_username:  thvasilo

# Build settings
markdown: kramdown # redcarpet TODO: Github pages now only supports kramdown, need to switch over and fix math
